# Tomographic bins (allowed range: [1,10])
binX: 2
binY: 3
# Binning of photometric probes (allowed range: [10,5000])
ltype: 'log'
lmin: 10
lmax: 5000
nl: 1000
# Style settings for photometric probes
photo_colours: 'r'
photo_linestyle: 'dashed'
# Redshift (allowed range: [0.,1.8])
redshift: 1.3
# Binning of GC-Spec multipoles (allowed range: [0.001,0.5])
ktype: 'log'
kmin: 0.001
kmax: 0.5
nk: 1000
# Style settings for multipoles
spec_colours: ['C0', 'C1', 'C2']
spec_linestyle: 'solid'
# Output
path: 'output/'
# Output file names
file_WL: 'CLOE_WL_predictions'
file_GCphot: 'CLOE_GCphot_predictions'
file_XC: 'CLOE_XC_predictions'
file_GCspec: 'CLOE_GCspec_predictions'
