default:
  image: gitlab.euclid-sgs.uk:4567/pf-ist-likelihood/likelihood-implementation

# Caches
cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .pytest_cache

# Install dependencies
before_script:
  - source activate cloe
  - conda list
  - ls -a
  - echo $CI_PIPELINE_SOURCE

# Run unit tests
Tests:
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  script:
    - python -m pytest
  only:
    refs:
      - merge_requests
    changes:
      - cloe/*
      - cloe/**/*
      - configs/*
      - data/ExternalBenchmark/*
      - environment.yml
      - .gitlab-ci.yml
      - setup.cfg
  artifacts:
    reports:
      junit: pytest.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

# Run verification tests
Verification:
  script:
    - python -m pytest cloe/tests/verification
  when: manual
  artifacts:
    reports:
      junit: pytest.xml
  only:
    - merge_requests

# Build temporary API docs for reviewer
Check_HTML:
  script:
    - &apidoc_build_script |
      mkdir docs/build
      sphinx-apidoc -feo docs/source cloe
      sphinx-build docs/source docs/build
    - mv docs/build html_build
  when: manual
  artifacts:
    paths:
      - html_build/
    expose_as: 'API HTML Build'
  only:
    - merge_requests

# Build API docs for deployment
pages:
  script:
    - *apidoc_build_script
    - mv docs/build public/
  artifacts:
    paths:
      - public
  only:
      - master

# Get Profiling Report
Profiling:
  script:
    - python -m cProfile -o evaluate_likelihood.pstats run_cloe.py configs/config_profiling_evaluate_likelihood.yaml
    - python -m cProfile -o mcmc.pstats run_cloe.py configs/config_profiling_mcmc.yaml
    - mkdir products
    - mv *.pstats products/
  when: manual
  artifacts:
    paths:
      - products/
    expose_as: 'Profiling Report'
  only:
    - merge_requests
    - master
