default:
  image: gitlab.euclid-sgs.uk:4567/pf-ist-likelihood/likelihood-implementation

# Caches
cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .pytest_cache

# Install dependencies
before_script:
  - source activate cloe
  - conda list
  - ls -a
  - echo $CI_PIPELINE_SOURCE

# Install package
Install:
  script:
    - python setup.py test
  only:
    refs:
      - merge_requests
    changes:
      - likelihood/*
      - likelihood/**/*
      - configs/*
      - data/ExternalBenchmark/*
      - environment.yml
      - .gitlab-ci.yml
      - setup.cfg
  artifacts:
    reports:
      junit: pytest.xml
      cobertura: coverage.xml

# Build temporary API docs for reviewer
Check_HTML:
  script:
    - &apidoc_build_script |
      mkdir docs/build
      sphinx-apidoc -feo docs/source likelihood
      sphinx-build docs/source docs/build
    - mv docs/build html_build
  when: manual
  artifacts:
    paths:
      - html_build/
    expose_as: 'API HTML Build'
  only:
    - merge_requests

# Build API docs for deployment
pages:
  script:
    - *apidoc_build_script
    - mv docs/build public/
  artifacts:
    paths:
      - public
  only:
      - master

# Get Profiling Report
Profiling:
  script:
    - python profiling.py 1
    - python -m cProfile -o profiling.pstats profiling.py
    - mkdir products
    - mv profiling.pstats products/
  when: manual
  artifacts:
    paths:
      - products/
    expose_as: 'Profiling Report'
  only:
    - merge_requests
    - master
