# Install dependencies
before_script:
  - apt-get update
  - apt-get upgrade -y
  - apt-get install software-properties-common -y
  - add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) main universe restricted multiverse"
  - apt-get install gfortran -y
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda env create -f environment.yml
  - source activate likelihood
  - pip install coverage nose pytest pytest-cov

# Install package
Install:
  script: python setup.py test
  artifacts:
    when: always
    reports:
      junit: pytest.xml
      cobertura: coverage.xml

# Build temporary API docs for reviewer
Check_HTML:
  script:
    - &build_script |
      source activate likelihood
      pip install sphinx sphinx-rtd-theme numpydoc
      mkdir docs/build
      sphinx-apidoc -feo docs/source likelihood
      sphinx-build docs/source docs/build
    - mv docs/build html_build
  artifacts:
    paths:
      - html_build/
    expose_as: 'API HTML Build'
  except:
      - master

# Build API docs for deployment
pages:
  script:
    - *build_script
    - mv docs/build public/
  artifacts:
    paths:
      - public
  only:
      - master

# Get Profiling Report
Profiling:
  script: 
    - python profiling.py 1
    - python -m cProfile -o profiling.pstats profiling.py
    - mkdir products
    - mv profiling.pstats products/
  artifacts:
    paths:
      - products/
    expose_as: 'Profiling Report'
