name: cloe
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - astropy>=4.0
  - camb==1.3.0
  - fast-pt>=3.1
  - jupyter>=1.0
  - matplotlib>=3.1
  - numpy>=1.17
  - scipy>=1.3
  - pip>=19.0
  - mpi4py>=3.0.3
  - seaborn>=0.11.2
  - pip:
    #- git+https://github.com/CobayaSampler/cobaya
    - cobaya==3.1.0
    # baccoemu needs to be commented out in order to build the conda
    # environment layer in the Docker image
    # - baccoemu>=1.1
    - pytest>=6.2
    - pytest-cov>=2.10
    - pytest-pycodestyle>=2.2.0
    - pytest-pydocstyle>=2.2.0
    - sphinx
    - sphinx-rtd-theme
    - numpydoc
