name: cosmobox
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - matplotlib>=3.1
  - numpy>=1.17
  - pip>=19.0
  - scipy>=1.3
  - jupyter>=1.0
  - pip:
    - camb>=1.0
    - pytest
    - pytest-cov
    - pytest-pep8
