name: likelihood
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - astropy>=4.0
  - camb>=1.3
  - fast-pt>=3.1
  - jupyter>=1.0
  - matplotlib>=3.1
  - numpy>=1.17
  - scipy>=1.3
  - pip>=19.0
  - mpi4py>=3.0.3
  - pip:
    - baccoemu>=1.1
    - git+https://github.com/CobayaSampler/cobaya
    - pytest>=6.2
    - pytest-cov>=2.10
    - pytest-pycodestyle>=2.2.0
    - pytest-pydocstyle>=2.2.0
