backend: Cobaya
Cobaya:
  debug: true
  force: true
  likelihood:
    Euclid: !!python/name:likelihood.cobaya_interface.EuclidLikelihood ''
  output: chains/my_euclid_experiment
  params:
    As: 2.12605e-09
    H0: 67
    N_eff: null
    mnu: 0.06
    nnu: 3.046
    ns:
      prior:
        max: 1.2
        min: 0.8
    ombh2: 0.022445
    omch2: 0.1205579307
    omegab: null
    omegac: null
    omegam: null
    omeganu: null
    omk: 0.0
    omnuh2: null
    tau: 0.0925
    w: -1
    wa: 0
  sampler:
    evaluate: null
  theory:
    camb:
      extra_args:
        dark_energy_model: ppf
        num_massive_neutrinos: 1
      stop_at_error: true
  timing: true
data:
  sample: 'ExternalBenchmark'
  spec:
    root: cov_power_galaxies_dk0p004_z{:s}.fits
    redshifts: ["1.", "1.2", "1.4", "1.65"]
  photo:
    ndens_GC: niTab-EP10-RB00.dat
    ndens_WL: niTab-EP10-RB00.dat
    root_GC: Cls_{:s}_PosPos.fits
    root_WL: Cls_{:s}_ShearShear.fits
    root_XC: Cls_{:s}_PosShear.fits
    IA_model: zNLA
    cov_GC: CovMat-PosPos-{:s}-20Bins.dat
    cov_WL: CovMat-ShearShear-{:s}-20Bins.dat
    cov_3x2: CovMat-3x2pt-{:s}-20Bins.dat
    cov_model: Gauss
