As: 2.12605e-09
H0: 67.0
N_eff: null
mnu: 0.06
nnu: 3.046
ns:
  prior:
    max: 1.2
    min: 0.8
ombh2: 0.022445
omch2: 0.1205579307
omegab: null
omegac: null
omegam: null
omeganu: null
omk: 0.0
omnuh2: null
tau: 0.0925
w: -1.0
wa: 0.0
