b2_photo_bin1: 0.0
b2_photo_bin2: 0.0
b2_photo_bin3: 0.0
b2_photo_bin4: 0.0
b2_photo_bin5: 0.0
b2_photo_bin6: 0.0
b2_photo_bin7: 0.0
b2_photo_bin8: 0.0
b2_photo_bin9: 0.0
b2_photo_bin10: 0.0
b2_photo_bin11: 0.0
b2_photo_bin12: 0.0
b2_photo_bin13: 0.0
bG2_photo_bin1: 0.0
bG2_photo_bin2: 0.0
bG2_photo_bin3: 0.0
bG2_photo_bin4: 0.0
bG2_photo_bin5: 0.0
bG2_photo_bin6: 0.0
bG2_photo_bin7: 0.0
bG2_photo_bin8: 0.0
bG2_photo_bin9: 0.0
bG2_photo_bin10: 0.0
bG2_photo_bin11: 0.0
bG2_photo_bin12: 0.0
bG2_photo_bin13: 0.0
bG3_photo_bin1: 0.0
bG3_photo_bin2: 0.0
bG3_photo_bin3: 0.0
bG3_photo_bin4: 0.0
bG3_photo_bin5: 0.0
bG3_photo_bin6: 0.0
bG3_photo_bin7: 0.0
bG3_photo_bin8: 0.0
bG3_photo_bin9: 0.0
bG3_photo_bin10: 0.0
bG3_photo_bin11: 0.0
bG3_photo_bin12: 0.0
bG3_photo_bin13: 0.0

b2_0_poly_photo: 0.0
b2_1_poly_photo: 0.0
b2_2_poly_photo: 0.0
b2_3_poly_photo: 0.0
bG2_0_poly_photo: 0.0
bG2_1_poly_photo: 0.0
bG2_2_poly_photo: 0.0
bG2_3_poly_photo: 0.0
bG3_0_poly_photo: 0.0
bG3_1_poly_photo: 0.0
bG3_2_poly_photo: 0.0
bG3_3_poly_photo: 0.0

b2_spectro_bin1: 0.0
b2_spectro_bin2: 0.0
b2_spectro_bin3: 0.0
b2_spectro_bin4: 0.0
bG2_spectro_bin1: 0.0
bG2_spectro_bin2: 0.0
bG2_spectro_bin3: 0.0
bG2_spectro_bin4: 0.0
bG3_spectro_bin1: 0.0
bG3_spectro_bin2: 0.0
bG3_spectro_bin3: 0.0
bG3_spectro_bin4: 0.0
c0_spectro_bin1: 0.0
c0_spectro_bin2: 0.0
c0_spectro_bin3: 0.0
c0_spectro_bin4: 0.0
c2_spectro_bin1: 0.0
c2_spectro_bin2: 0.0
c2_spectro_bin3: 0.0
c2_spectro_bin4: 0.0
c4_spectro_bin1: 0.0
c4_spectro_bin2: 0.0
c4_spectro_bin3: 0.0
c4_spectro_bin4: 0.0
ck4_spectro_bin1: 0.0
ck4_spectro_bin2: 0.0
ck4_spectro_bin3: 0.0
ck4_spectro_bin4: 0.0
aP_spectro_bin1: 0.0
aP_spectro_bin2: 0.0
aP_spectro_bin3: 0.0
aP_spectro_bin4: 0.0
Psn_spectro_bin1: 0.0
Psn_spectro_bin2: 0.0
Psn_spectro_bin3: 0.0
Psn_spectro_bin4: 0.0
e0k2_spectro_bin1: 0.0
e0k2_spectro_bin2: 0.0
e0k2_spectro_bin3: 0.0
e0k2_spectro_bin4: 0.0
e2k2_spectro_bin1: 0.0
e2k2_spectro_bin2: 0.0
e2k2_spectro_bin3: 0.0
e2k2_spectro_bin4: 0.0
