multiplicative_bias_1: 0.0
multiplicative_bias_2: 0.0
multiplicative_bias_3: 0.0
multiplicative_bias_4: 0.0
multiplicative_bias_5: 0.0
multiplicative_bias_6: 0.0
multiplicative_bias_7: 0.0
multiplicative_bias_8: 0.0
multiplicative_bias_9: 0.0
multiplicative_bias_10: 0.0
multiplicative_bias_11: 0.0
multiplicative_bias_12: 0.0
multiplicative_bias_13: 0.0
