magnification_bias_1: 0.0
magnification_bias_2: 0.0
magnification_bias_3: 0.0
magnification_bias_4: 0.0
magnification_bias_5: 0.0
magnification_bias_6: 0.0
magnification_bias_7: 0.0
magnification_bias_8: 0.0
magnification_bias_9: 0.0
magnification_bias_10: 0.0
b0_mag_poly: -1.50685
b1_mag_poly: 1.35034
b2_mag_poly: 0.08321
b3_mag_poly: 0.04279
