luminosity_slope_1: 0.4
luminosity_slope_2: 0.4
luminosity_slope_3: 0.4
luminosity_slope_4: 0.4
luminosity_slope_5: 0.4
luminosity_slope_6: 0.4
luminosity_slope_7: 0.4
luminosity_slope_8: 0.4
luminosity_slope_9: 0.4
luminosity_slope_10: 0.4