dz_1_GCphot: 0.0
dz_1_WL: 0.0
dz_2_GCphot: 0.0
dz_2_WL: 0.0
dz_3_GCphot: 0.0
dz_3_WL: 0.0
dz_4_GCphot: 0.0
dz_4_WL: 0.0
dz_5_GCphot: 0.0
dz_5_WL: 0.0
dz_6_GCphot: 0.0
dz_6_WL: 0.0
dz_7_GCphot: 0.0
dz_7_WL: 0.0
dz_8_GCphot: 0.0
dz_8_WL: 0.0
dz_9_GCphot: 0.0
dz_9_WL: 0.0
dz_10_GCphot: 0.0
dz_10_WL: 0.0
dz_11_GCphot: 0.0
dz_11_WL: 0.0
dz_12_GCphot: 0.0
dz_12_WL: 0.0
dz_13_GCphot: 0.0
dz_13_WL: 0.0
sigma_z: 0.002
