Cobaya:
  debug: true
  force: true
  likelihood:
    Euclid:
      NL_flag: 0
      add_phot_RSD: false
      aliases:
      - euclid
      data: data.yaml
      external: !!python/name:cloe.cobaya_interface.EuclidLikelihood ''
      f_out_z_dep: false
      observables_selection: observables_selection.yaml
      observables_specifications:
        GCphot: GCphot.yaml
        GCphot-GCspectro: GCphot-GCspectro.yaml
        GCspectro: GCspectro.yaml
        WL: WL.yaml
        WL-GCphot: WL-GCphot.yaml
        WL-GCspectro: WL-GCspectro.yaml
      plot_observables_selection: false
      speed: 500
      use_gamma_MG: true
  output: chains/my_euclid_experiment_gamma_w0waCDM_nonflat
  params: ./extra_config_cases/model_gamma_w0waCDM_nonflat.yaml
  sampler:
    mcmc:
      max_tries: 100000
  theory:
    camb:
      extra_args:
        dark_energy_model: ppf
        num_massive_neutrinos: 1
      stop_at_error: true
  timing: true
action: run
backend: Cobaya
