Cobaya:
  debug: true
  force: true
  likelihood:
    Euclid:
      NL_flag_phot_matter: 0
      NL_flag_spectro: 0
      add_phot_RSD: false
      aliases:
      - euclid
      bias_model: 1
      data: data.yaml
      external: !!python/name:cloe.cobaya_interface.EuclidLikelihood ''
      f_out_z_dep: false
      k_max_extrap: 500.0
      k_min_extrap: 1.0e-05
      k_samp: 1000
      magbias_model: 2
      observables_selection: observables_selection.yaml
      observables_specifications:
        GCphot: GCphot.yaml
        GCphot-GCspectro: GCphot-GCspectro.yaml
        GCspectro: GCspectro.yaml
        WL: WL.yaml
        WL-GCphot: WL-GCphot.yaml
        WL-GCspectro: WL-GCspectro.yaml
      plot_observables_selection: false
      solver: camb
      speed: 500
      statistics_spectro: legendre_multipole_power_spectrum
      use_gamma_MG: true
      z_max: 4.0
      z_min: 0.0
      z_samp: 100
  output: chains/my_euclid_experiment_gamma_w0waCDM_nonflat
  params: ./extra_config_cases/model_gamma_w0waCDM_nonflat.yaml
  sampler:
    mcmc:
      max_tries: 100000
  theory:
    camb:
      extra_args: {}
      stop_at_error: true
  timing: true
action: run
backend: Cobaya
