user_models:
  cosmology: extra_cosmologies/cosmology_wCDM.yaml
  modified_gravity: modified_gravity.yaml
  nuisance_bias: nuisance_bias.yaml
  nuisance_ia: nuisance_ia.yaml
  nuisance_magnification_bias: nuisance_magnification_bias.yaml
  nuisance_nz: nuisance_nz.yaml
  nuisance_purity: nuisance_purity.yaml
  nuisance_shear_calibration: nuisance_shear_calibration.yaml
  nonlinearities: nonlinearities.yaml
user_options:
  overwrite: true
