As:
  latex: A_\mathrm{s}
  value: 'lambda logA: 1e-10*np.exp(logA)'
H0:
  latex: H_0
  prior:
    max: 100.0
    min: 40.0
  proposal: 0.5
  ref:
    dist: norm
    loc: 67.0
    scale: 1.0
gamma_MG:
  latex: \gamma
  prior:
    max: 1.0
    min: 0.1
  proposal: 0.1
  ref:
    dist: norm
    loc: 0.55
    scale: 0.1
logA:
  drop: true
  latex: \log(10^{10} A_\mathrm{s})
  prior:
    max: 7.0
    min: 1.6
  proposal: 0.001
  ref:
    dist: norm
    loc: 3.05
    scale: 0.001
mnu: 0.06
nnu: 3.046
ns:
  latex: n_\mathrm{s}
  prior:
    max: 1.2
    min: 0.6
  proposal: 0.002
  ref:
    dist: norm
    loc: 0.96
    scale: 0.004
num_nu_massive: 1
ombh2:
  latex: \Omega_\mathrm{b} h^2
  prior:
    max: 0.1
    min: 0.005
  proposal: 0.0001
  ref:
    dist: norm
    loc: 0.0224
    scale: 0.0001
omch2:
  latex: \Omega_\mathrm{c} h^2
  prior:
    max: 0.99
    min: 0.001
  proposal: 0.0005
  ref:
    dist: norm
    loc: 0.12
    scale: 0.001
omegab:
  derived: 'lambda ombh2, H0: ombh2 * (100.0/H0)**2'
  latex: \Omega_\mathrm{b}
omegam:
  latex: \Omega_\mathrm{m}
omk:
  latex: \Omega_k
  prior:
    max: 0.1
    min: -0.1
  proposal: 0.05
  ref:
    dist: norm
    loc: 0
    scale: 0.05
sigma8:
  latex: \sigma_8
tau: 0.0925
use_ppf: true
w:
  latex: w_0
  prior:
    max: -0.5
    min: -3.0
  proposal: 0.5
  ref:
    dist: norm
    loc: -1
    scale: 0.5
wa:
  latex: w_a
  prior:
    max: 0.5
    min: -3.0
  proposal: 0.1
  ref:
    dist: norm
    loc: 0
    scale: 0.1
