backend: Cobaya
Cobaya:
  debug: true
  force: false
  likelihood:
    Euclid:
      aliases:
      - euclid
      external: !!python/name:likelihood.cobaya_interface.EuclidLikelihood ''
      NL_flag: 0
      # The fields 'data', 'observables_selection', and 'observables_specifications'
      # are by default the ones in ../likelihood/EuclidLikelihood.yaml
      # The user can overwrite here their values.
      # - by specifying a yaml file
      # - by specifying a dictionary (in yaml format)
      # Please note that if specifying a dictionary, all the fields must be present
  output: chains/my_euclid_experiment
  params: ./model_default.yaml
  sampler:
    mcmc:
      max_tries: 100000
  theory:
    camb:
      extra_args:
        dark_energy_model: ppf
        num_massive_neutrinos: 1
      stop_at_error: true
  timing: true

