backend: Cobaya
Cobaya:
  # Documentation about Cobaya keys can be found at:
  # https://cobaya.readthedocs.io/en/latest/cosmo_basic_runs.html
  debug: true
  force: true
  likelihood:
    Euclid:
      aliases:
      - euclid
      external: !!python/name:cloe.cobaya_interface.EuclidLikelihood ''
      # Speed in evaluations/second
      speed: 500
      # Non-Linear flag selector
      NL_flag: 0
      # Add RSD to photometric probes
      add_phot_RSD: False
      # Use MG gamma
      use_gamma_MG: False
      # Redshift dependent purity correction
      f_out_z_dep: False
      # Plot the selected observables during the initialization of the likelihood
      plot_observables_selection: False
      ##
      # The user can overwrite here the values of
      # the fields 'data', 'observables_selection', and 'observables_specifications':
      # - by specifying a yaml file
      # - by specifying a dictionary (in yaml format)
      # Please note that if specifying a dictionary, all the fields must be present
      ##
      # Information about where the data is stored
      data: data.yaml
      # Selection of the observables to be computed
      observables_selection: observables_selection.yaml
      # Specifications for each of the observables
      observables_specifications:
        GCphot: GCphot.yaml
        GCspectro: GCspectro.yaml
        WL: WL.yaml
        WL-GCphot: WL-GCphot.yaml
        # Note: This is not yet provided by CLOE
        # therefore it will load empty dictionaries
        GCphot-GCspectro: GCphot-GCspectro.yaml
        WL-GCspectro: WL-GCspectro.yaml
  output: chains/my_euclid_experiment
  params: ./model_default.yaml
  sampler:
    mcmc:
      max_tries: 100000
  theory:
    camb:
      extra_args:
        dark_energy_model: ppf
        num_massive_neutrinos: 1
      stop_at_error: true
  timing: true
action: run
