backend: Cobaya
Cobaya:
  debug: true
  force: true
  likelihood:
    Euclid:
      aliases:
      - euclid
      external: !!python/name:likelihood.cobaya_interface.EuclidLikelihood ''
      NL_flag: 0
      plot_observables_selection: False
      # The fields 'data', 'observables_selection', and 'observables_specifications'
      # are by default the ones in ../likelihood/EuclidLikelihood.yaml
      # The user can overwrite here their values:
      # - by specifying a yaml file (as here in the case of data, and the probe files)
      # - by specifying a dictionary, in yaml format (as here in the case of observables_selection)
      data: data.yaml
      observables_selection:
        WL:
          WL: True
          GCphot: False
          GCspectro: False
        GCphot:
          GCphot: True
          GCspectro: False
        GCspectro:
          GCspectro: True
      observables_specifications:
        GCphot: GCphot.yaml
        GCspectro: GCspectro.yaml
        WL: WL.yaml
        GCphot-GCspectro: GCphot-GCspectro.yaml
        WL-GCphot: WL-GCphot.yaml
        WL-GCspectro: WL-GCspectro.yaml
  output: chains/my_euclid_experiment
  params: ./model_test.yaml
  sampler:
    evaluate: null
  theory:
    camb:
      extra_args:
        dark_energy_model: ppf
        num_massive_neutrinos: 1
      stop_at_error: true
  timing: true

