backend: Cobaya
Cobaya:
  debug: true
  force: true
  likelihood:
    Euclid:
      aliases:
      - euclid
      external: !!python/name:likelihood.cobaya_interface.EuclidLikelihood ''
      NL_flag: 0
      data:
        sample: 'ExternalBenchmark'
        spectro:
          root: cov_power_galaxies_dk0p004_z{:s}.fits
          redshifts: [ "1.", "1.2", "1.4", "1.65" ]
        photo:
          ndens_GC: niTab-EP10-RB00.dat
          ndens_WL: niTab-EP10-RB00.dat
          root_GC: Cls_{:s}_PosPos.dat
          root_WL: Cls_{:s}_ShearShear.dat
          root_XC: Cls_{:s}_PosShear.dat
          IA_model: zNLA
          cov_GC: CovMat-PosPos-{:s}-20Bins.dat
          cov_WL: CovMat-ShearShear-{:s}-20Bins.dat
          cov_3x2: CovMat-3x2pt-{:s}-20Bins.dat
          cov_model: Gauss
  output: chains/my_euclid_experiment
  params: ./model_test.yaml
  sampler:
    evaluate: null
  theory:
    camb:
      extra_args:
        dark_energy_model: ppf
        num_massive_neutrinos: 1
      stop_at_error: true
  timing: true

