photo:
  redshifts:
  - 0.2095
  - 0.489
  - 0.619
  - 0.7335
  - 0.8445
  - 0.9595
  - 1.087
  - 1.2395
  - 1.45
  - 2.038
  luminosity_ratio: luminosity_ratio.dat
  IA_model: zNLA
  # Whether to use the (old) benchmark .dat files or OU-LE3-format FITS files
  photo_data: 'standard'
  # Fourier space covariance (cov_3x2pt)
  cov_3x2pt: CovMat-3x2pt-{:s}-20Bins.npz
  # Configuration space covariance (cov_3x2pt)
  # cov_3x2pt: cov_corr_func-3x2pt-Gauss-20Bins.npz
  cov_GC: CovMat-PosPos-{:s}-20Bins.npz
  cov_WL: CovMat-ShearShear-{:s}-20Bins.npz
  cov_model: Gauss
  cov_is_num: False
  cov_nsim: 10000
  ndens_GC: niTab-EP10-RB00.dat
  ndens_WL: niTab-EP10-RB00.dat
  # Fourier space measurements (root_GC/WL/XC)
  root_GC: Cls_{:s}_PosPos.dat
  root_WL: Cls_{:s}_ShearShear.dat
  root_XC: Cls_{:s}_PosShear.dat
  # Configuration space measurements (root_GC/WL/XC)
  # root_GC: corr_func_zNLA_PosPos.dat
  # root_WL: corr_func_zNLA_ShearShear.dat
  # root_XC: corr_func_zNLA_PosShear.dat
  root_fits: fs2_cls_{:d}zbins_32ellbins.fits
  root_mixing_matrix: fs2_mms_10zbins_32ellbins.fits
  # Fourier needs to be consistent with probe statistics and data files
  Fourier: True
sample: ExternalBenchmark
spectro:
  redshifts:
  - '1.'
  - '1.2'
  - '1.4'
  - '1.65'
  edges:
  - 0.9
  - 1.1
  - 1.3
  - 1.5
  - 1.8
  # Fourier space measurements and covariance file (root)
  root: cov_power_galaxies_dk0p004_z{:s}.fits
  # Configuration space measurements and covariance file (root)
  # root: cov_corr_func_galaxies_ds1_z{:s}.fits
  cov_is_num: False
  cov_nsim: 3500
  scale_cuts_fourier: GCspectro-FourierSpace.yaml
  root_mixing_matrix: mm_FS230degCircle_m3_nosm_obsz_z0.9-1.1.fits
  # Fourier needs to be consistent with probe statistics and data files
  Fourier: True
cmbx:
  root_CMBlens: Cls_kCMB.dat
  root_CMBlensxWL: Cls_kCMBxWL.dat
  root_CMBlensxGC: Cls_kCMBxGC.dat
  root_CMBisw: Cls_{:s}_ISWxGC.dat
  ISW_model: zNLA
  cov_7x2pt: Cov_7x2pt_WL_GC_CMBX.npy
CG:
  file_names_CC: data_CG_CC.dat
  file_cov_names_CC: data_cov_CG_CC.dat
  file_names_MoR: data_CG_MoR.dat
  file_cov_names_MoR: data_cov_CG_MoR.dat
  file_names_xi2: data_CG_xi2.npy
  file_cov_names_xi2: data_cov_CG_xi2.npy
