# This yaml file contains the user specifications 
# about the scales and redshift/tomographic bins 
# of the Euclid data to include 
# in the likelihood analysis.
#
# PROBE: GCphot-GCspectro 
# cross-corrrelation power spectrum
#
# GCphot: Galaxy Clustering photometric
# GCspectro: Galaxy Clustering spectroscopic
#
# Note: this is not yet provided by CLOE
