# This yaml file contains the user specifications 
# about the scales and redshift/tomographic bins 
# of the Euclid data to include 
# in the likelihood analysis.
# 
# PROBE: GCphot auto-correlation power spectrum
#
# GCphot: Number density fluctuations of 
# the photometric galaxy sample
#
# Note: For a given tomographic bin combination, 
# the range of angular scales (in multipoles ell) 
# can be concatenated as for example
# ell_range: [[20, 400], [401, 4000]]
# To exclude all angular scales, 
# an empty list can be provided
statistics: angular_power_spectrum
bins:
  n1: 
    n1: 
      ell_range: [[20, 4000]]
    n2: 
      ell_range: [[20, 4000]]
    n3: 
      ell_range: [[20, 4000]]
    n4: 
      ell_range: [[20, 4000]]
    n5: 
      ell_range: [[20, 4000]]
    n6: 
      ell_range: [[20, 4000]]
    n7: 
      ell_range: [[20, 4000]]
    n8: 
      ell_range: [[20, 4000]]
    n9: 
      ell_range: [[20, 4000]]
    n10: 
      ell_range: [[20, 4000]]
  n2: 
    n2: 
      ell_range: [[20, 4000]]
    n3: 
      ell_range: [[20, 4000]]
    n4: 
      ell_range: [[20, 4000]]
    n5: 
      ell_range: [[20, 4000]]
    n6: 
      ell_range: [[20, 4000]]
    n7: 
      ell_range: [[20, 4000]]
    n8: 
      ell_range: [[20, 4000]]
    n9: 
      ell_range: [[20, 4000]]
    n10: 
      ell_range: [[20, 4000]]
  n3: 
    n3: 
      ell_range: [[20, 4000]]
    n4: 
      ell_range: [[20, 4000]]
    n5: 
      ell_range: [[20, 4000]]
    n6: 
      ell_range: [[20, 4000]]
    n7: 
      ell_range: [[20, 4000]]
    n8: 
      ell_range: [[20, 4000]]
    n9: 
      ell_range: [[20, 4000]]
    n10: 
      ell_range: [[20, 4000]]
  n4: 
    n4: 
      ell_range: [[20, 4000]]
    n5: 
      ell_range: [[20, 4000]]
    n6: 
      ell_range: [[20, 4000]]
    n7: 
      ell_range: [[20, 4000]]
    n8: 
      ell_range: [[20, 4000]]
    n9: 
      ell_range: [[20, 4000]]
    n10: 
      ell_range: [[20, 4000]]
  n5: 
    n5: 
      ell_range: [[20, 4000]]
    n6: 
      ell_range: [[20, 4000]]
    n7: 
      ell_range: [[20, 4000]]
    n8: 
      ell_range: [[20, 4000]]
    n9: 
      ell_range: [[20, 4000]]
    n10: 
      ell_range: [[20, 4000]]
  n6: 
    n6: 
      ell_range: [[20, 4000]]
    n7: 
      ell_range: [[20, 4000]]
    n8: 
      ell_range: [[20, 4000]]
    n9: 
      ell_range: [[20, 4000]]
    n10: 
      ell_range: [[20, 4000]]
  n7: 
    n7: 
      ell_range: [[20, 4000]]
    n8: 
      ell_range: [[20, 4000]]
    n9: 
      ell_range: [[20, 4000]]
    n10: 
      ell_range: [[20, 4000]]
  n8: 
    n8: 
      ell_range: [[20, 4000]]
    n9: 
      ell_range: [[20, 4000]]
    n10: 
      ell_range: [[20, 4000]]
  n9: 
    n9: 
      ell_range: [[20, 4000]]
    n10: 
      ell_range: [[20, 4000]]
  n10: 
    n10: 
      ell_range: [[20, 4000]]
