# This yaml file contains the user specifications 
# about the scales and redshift/tomographic bins 
# of the Euclid data to include 
# in the likelihood analysis.
#
# PROBE: GCphot-GCspectro 
# cross-corrrelation power spectrum
#
# GCphot: Number density fluctuations of 
# the photometric galaxy sample
# GCspectro: Number density fluctuations of 
# the spectroscopic galaxy sample
# Note: this is not yet provided by CLOE
