# This yaml file contains the user specifications 
# for the Euclid observables computed theoretically
# in CLOE.
# 
# PROBE: GCspectro
#
# GCspectro: Galaxy Clustering spectroscopic
#
# Note: you can concatenate k_ranges as
# i.e: k_range: [[0.01, 0.2], [0.3, 0.5]]
statistics: legendre_multipole_power_spectrum
bins:
  n1: 
    n1:
      multipoles:
        0:
          k_range: [[0.01, 0.5]]
        2: 
          k_range: [[0.01, 0.5]]
        4:
          k_range: [[0.01, 0.5]]
  n2: 
    n2:
      multipoles:
        0:
          k_range: [[0.01, 0.5]]
        2:
          k_range: [[0.01, 0.5]]
        4:
          k_range: [[0.01, 0.5]]
  n3: 
    n3: 
      multipoles:
        0:
          k_range: [[0.01, 0.5]]
        2:
          k_range: [[0.01, 0.5]]
        4:
          k_range: [[0.01, 0.5]]
  n4: 
    n4:
      multipoles:
        0:
          k_range: [[0.01, 0.5]]
        2:
          k_range: [[0.01, 0.5]]
        4:
          k_range: [[0.01, 0.5]]
