# File paths in user_models are relative to the configs/models/ directory
user_models:
  cosmology: cosmology.yaml
  nuisance_bias: nuisance_bias.yaml
  nuisance_ia: nuisance_ia.yaml
  nuisance_nz: nuisance_nz.yaml
  nuisance_shear_calibration: nuisance_shear_calibration.yaml
user_options:
  # Flag for advanced users to let CLOE overwrite the configs/params.yaml file
  overwrite: False
