# File paths in user_models are relative to the configs/models/ directory
user_models:
  cosmology: cosmology_only_ns_free.yaml
  nuisance_bias: nuisance_bias.yaml
  nuisance_ia: nuisance_ia.yaml
  nuisance_nz: nuisance_nz.yaml
user_options:
  # Overwrite configs/params.yaml ?
  overwrite: False
