user_models:
  cosmology: cosmology.yaml
  likelihood_flags: likelihood_flags.yaml
  nuisance_bias: nuisance_bias.yaml
  nuisance_ia: nuisance_ia.yaml
  spectro: spectro.yaml
user_options:
  model_path: ./configs/models
  out_params_yaml_path: ./likelihood/params.yaml
  overwrite: true
