# This is a default input file used by the Cobaya interface.
# Users should never edit this file.

# Intrinsic alignment
aia: 1.72
bia: 0.0
nia: -0.41
# Photometric galaxy bias (IST:F case)
b1_photo: 1.0997727037892875
b2_photo: 1.220245876862528
b3_photo: 1.2723993083933989
b4_photo: 1.316624471897739
b5_photo: 1.35812370570578
b6_photo: 1.3998214171814918
b7_photo: 1.4446452851824907
b8_photo: 1.4964959071110084
b9_photo: 1.5652475842498528
b10_photo: 1.7429859437184225
# Photometric galaxy bias (polynomial case)
b0_poly_photo: 0.830703
b1_poly_photo: 1.190547
b2_poly_photo: -0.928357
b3_poly_photo: 0.423292
# Magnification bias
magnification_bias_1: 0.0
magnification_bias_2: 0.0
magnification_bias_3: 0.0
magnification_bias_4: 0.0
magnification_bias_5: 0.0
magnification_bias_6: 0.0
magnification_bias_7: 0.0
magnification_bias_8: 0.0
magnification_bias_9: 0.0
magnification_bias_10: 0.0
# Multiplicative bias
multiplicative_bias_1: 0.0
multiplicative_bias_2: 0.0
multiplicative_bias_3: 0.0
multiplicative_bias_4: 0.0
multiplicative_bias_5: 0.0
multiplicative_bias_6: 0.0
multiplicative_bias_7: 0.0
multiplicative_bias_8: 0.0
multiplicative_bias_9: 0.0
multiplicative_bias_10: 0.0
# Uncertainty in photometric bins
dz_1_GCphot: 0.0
dz_1_WL: 0.0
dz_2_GCphot: 0.0
dz_2_WL: 0.0
dz_3_GCphot: 0.0
dz_3_WL: 0.0
dz_4_GCphot: 0.0
dz_4_WL: 0.0
dz_5_GCphot: 0.0
dz_5_WL: 0.0
dz_6_GCphot: 0.0
dz_6_WL: 0.0
dz_7_GCphot: 0.0
dz_7_WL: 0.0
dz_8_GCphot: 0.0
dz_8_WL: 0.0
dz_9_GCphot: 0.0
dz_9_WL: 0.0
dz_10_GCphot: 0.0
dz_10_WL: 0.0
# Growth rate index for scenario different from GR
gamma_MG: 0.55
# Spectroscopic galaxy bias
b1_spectro_bin1: 1.46
b1_spectro_bin2: 1.61
b1_spectro_bin3: 1.75
b1_spectro_bin4: 1.9
b2_spectro_bin1: 0.0
b2_spectro_bin2: 0.0
b2_spectro_bin3: 0.0
b2_spectro_bin4: 0.0
# Finger of God counterterms
c0_spectro_bin1: 0.0
c0_spectro_bin2: 0.0
c0_spectro_bin3: 0.0
c0_spectro_bin4: 0.0
c2_spectro_bin1: 0.0
c2_spectro_bin2: 0.0
c2_spectro_bin3: 0.0
c2_spectro_bin4: 0.0
c4_spectro_bin1: 0.0
c4_spectro_bin2: 0.0
c4_spectro_bin3: 0.0
c4_spectro_bin4: 0.0
# Shot noise parameters
aP_spectro_bin1: 0.0
aP_spectro_bin2: 0.0
aP_spectro_bin3: 0.0
aP_spectro_bin4: 0.0
Psn_spectro_bin1: 0.0
Psn_spectro_bin2: 0.0
Psn_spectro_bin3: 0.0
Psn_spectro_bin4: 0.0
# Purity of spectroscopic samples
f_out: 0.0
f_out_1: 0.0
f_out_2: 0.0
f_out_3: 0.0
f_out_4: 0.0
