# Spectro probe: linear galaxy bias
b1_spectro_bin1: 1.414
b1_spectro_bin2: 1.775
b1_spectro_bin3: 2.042
b1_spectro_bin4: 2.500
# Spectro probe: quadratic galaxy bias
b2_spectro_bin1: 1.061
b2_spectro_bin2: 1.433
b2_spectro_bin3: 1.903
b2_spectro_bin4: 2.970
# Spectro probe: nonlocal quadratic galaxy bias
bG2_spectro_bin1: 0.0
bG2_spectro_bin2: 0.0
bG2_spectro_bin3: 0.0
bG2_spectro_bin4: 0.0
# Spectro probe: nonlocal cubic galaxy bias
bG3_spectro_bin1: 0.0
bG3_spectro_bin2: 0.0
bG3_spectro_bin3: 0.0
bG3_spectro_bin4: 0.0
# Spectro probe: EFT counter terms
c0_spectro_bin1: 6.490
c0_spectro_bin2: 4.398
c0_spectro_bin3: 3.323
c0_spectro_bin4: 2.618
c2_spectro_bin1: 37.801
c2_spectro_bin2: 44.531
c2_spectro_bin3: 43.376
c2_spectro_bin4: 63.832
c4_spectro_bin1: 56.729
c4_spectro_bin2: 57.041
c4_spectro_bin3: 45.242
c4_spectro_bin4: 41.217
ck4_spectro_bin1: 0.0
ck4_spectro_bin2: 0.0
ck4_spectro_bin3: 0.0
ck4_spectro_bin4: 0.0
# Spectro probe: 1/bar(n)
Psn_spectro_bin1: 1627.758
Psn_spectro_bin2: 3231.92
Psn_spectro_bin3: 5680.44
Psn_spectro_bin4: 10608.98
# Spectro probe: corretion to Poissonian shot noise
aP_spectro_bin1: 0.053
aP_spectro_bin2: 0.139
aP_spectro_bin3: 0.151
aP_spectro_bin4: 0.311
# Spectro probe: scale-dependent shot noise
e0k2_spectro_bin1: 0.0
e0k2_spectro_bin2: 0.0
e0k2_spectro_bin3: 0.0
e0k2_spectro_bin4: 0.0
# Spectro probe: scale- and mu-dependent shot noise
e2k2_spectro_bin1: 0.0
e2k2_spectro_bin2: 0.0
e2k2_spectro_bin3: 0.0
e2k2_spectro_bin4: 0.0
# Spectro probe: unique purity nuisance parameter
f_out: 0.0
# Spectro probe: purity nuisance parameter per redshift bin
f_out_1: 0.195
f_out_2: 0.204
f_out_3: 0.306
f_out_4: 0.121
# Photometric probe: IA
aia: 1.72
nia: -0.41
bia: 2.17
# Photometric probe: polynomial galaxy bias
b0_poly_photo: 1.33291
b1_poly_photo: -0.72414
b2_poly_photo: 1.0183
b3_poly_photo: -0.14913
# Photometric probe: magnification polynomial galaxy bias
b0_mag_poly: -1.50685
b1_mag_poly: 1.35034
b2_mag_poly: 0.08321
b3_mag_poly: 0.04279
# Photometric probe: galaxy bias
b1_photo: 1.06533
b2_photo: 1.20449
b3_photo: 1.20498
b4_photo: 1.31719
b5_photo: 1.26084
b6_photo: 1.32578
b7_photo: 1.50557
b8_photo: 1.475
b9_photo: 1.45391
b10_photo: 1.52119
b11_photo: 1.63291
b12_photo: 2.01904
b13_photo: 2.61045
# Photometric probe: shift in redshift bins
dz_1_WL: -0.025749
dz_2_WL: 0.022716
dz_3_WL: -0.026032
dz_4_WL: 0.012594
dz_5_WL: 0.019285
dz_6_WL: 0.008326
dz_7_WL: 0.038207
dz_8_WL: 0.002732
dz_9_WL: 0.034066
dz_10_WL: 0.049479
dz_11_WL: 0.06649
dz_12_WL: 0.000815
dz_13_WL: 0.04907
dz_1_GCphot: -0.025749
dz_2_GCphot: 0.022716
dz_3_GCphot: -0.026032
dz_4_GCphot: 0.012594
dz_5_GCphot: 0.019285
dz_6_GCphot: 0.008326
dz_7_GCphot: 0.038207
dz_8_GCphot: 0.002732
dz_9_GCphot: 0.034066
dz_10_GCphot: 0.049479
dz_11_GCphot: 0.06649
dz_12_GCphot: 0.000815
dz_13_GCphot: 0.04907
# Theory: gamma parametrization for Modified Gravity (MG)
gamma_MG: 0.55
# Photometric probe: magnification galaxy bias
magnification_bias_1: -0.90815
magnification_bias_2: -0.9429000000000001
magnification_bias_3: -0.99905
magnification_bias_4: -0.8146499999999999
magnification_bias_5: -0.6452
magnification_bias_6: -0.77325
magnification_bias_7: -0.5683
magnification_bias_8: -0.2133999999999998
magnification_bias_9: -0.015200000000000102
magnification_bias_10: -0.04039999999999999
magnification_bias_11: 0.6398999999999999
magnification_bias_12: 0.91465
magnification_bias_13: 1.6853500000000001
# Photometric probe: purity nuisance parameters
multiplicative_bias_1: 0.0
multiplicative_bias_2: 0.0
multiplicative_bias_3: 0.0
multiplicative_bias_4: 0.0
multiplicative_bias_5: 0.0
multiplicative_bias_6: 0.0
multiplicative_bias_7: 0.0
multiplicative_bias_8: 0.0
multiplicative_bias_9: 0.0
multiplicative_bias_10: 0.0
multiplicative_bias_11: 0.0
multiplicative_bias_12: 0.0
multiplicative_bias_13: 0.0
# Pivot redshift for calculation of fIA
pivot_redshift: 0.0
