# This yaml file contains the user specifications 
# for the Euclid observables computed theoretically
# in CLOE.
#
# PROBE: WL-GCspectro cross-corrrelation
#
# WL: Weak Lensing
# GCspectro: Galaxy Clustering spectroscopic
#
# Note: this is not yet provided by CLOE
