# This yaml file contains the user specifications 
# about the scales and redshift/tomographic bins 
# of the Euclid data to include 
# in the likelihood analysis.
#
# Probe: WL-GCspectro cross-correlation
# power spectrum
#
# WL: Weak Lensing
# GCspectro: Number density fluctuations of 
# the spectroscopic galaxy sample 
# in redshift space
# 
# Note: this is not yet provided by CLOE
