name: Build & Push Docker Image

on:
  push:
    branches:
      - ci-debug
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build & push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/testnamemaster:ci-debug
            ghcr.io/${{ github.repository_owner }}/testnamemaster:latest

      - name: Confirm pushed
        run: |
          echo "ci-debug digest:"
          docker manifest inspect ghcr.io/${{ github.repository_owner }}/testnamemaster:ci-debug
          echo "latest digest:"
          docker manifest inspect ghcr.io/${{ github.repository_owner }}/testnamemaster:latest
