name: Build & Push Docker Image

on:
  push:
    branches: [ ci-debug ]
    paths:
      - 'Dockerfile'
      - 'environment.yml'
      - 'setup.cfg'
      - 'setup.py'
      - 'cloe/**'
      - '.github/workflows/build-and-push-image.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/testarnyttnamn/testnamemaster:latest
