name: Build & Push Docker Image

# trigger on pushes to ci-debug (or master/main if you like)
on:
  push:
    branches:
      - ci-debug

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read        # to check out the code
      packages: write       # to push to GHCR

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build & push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/testnamemaster:ci-debug

      - name: Confirm pushed
        run: |
          echo "Image digest:"
          docker run --rm ghcr.io/${{ github.repository_owner }}/testnamemaster:ci-debug sha256sum </dev/null || true
