name: CI Pipeline

on:
  pull_request: {}
  push:
    branches:
      - master
      - ci-debug
  workflow_dispatch: {}

jobs:
  build-and-push-image:
    name: Build & Publish Docker Image
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build & tag image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/likelihood-implementation:latest .

      - name: Push image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/likelihood-implementation:latest

  tests:
    name: Run pytest inside the container
    needs: build-and-push-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Pull latest image
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/likelihood-implementation:latest

      - name: Run pytest
        run: |
          docker run --rm \
            -v "${{ github.workspace }}":/src \
            -w /src \
            ghcr.io/${{ github.repository_owner }}/likelihood-implementation:latest \
            bash -lc "pytest --verbose --pycodestyle --pydocstyle \
              --junitxml=pytest.xml --cov=. --cov-report=xml=coverage.xml"

      - name: Upload JUnit report
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: pytest.xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
