name: Python Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
          environment-file: environment.yml
          activate-environment: cloe
          auto-activate-base: false

      - name: Install pip packages (if any left)
        run: |
          # pip installs from your environment.yml's pip section should be handled by conda
          # But if you want to force install (optional), uncomment:
          # pip install -r requirements.txt
          echo "Pip packages handled by conda environment"

      - name: Run pytest with coverage
        run: |
          pytest --cov=cloe --cov-report=term --cov-report=xml --junitxml=pytest.xml
