name: CI

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential gfortran make python3-dev python3-distutils

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.9
        activate-environment: cloe
        environment-file: environment.yml
        use-mamba: true

    - name: Debug conda env update
      run: |
        conda env update -n cloe -f environment.yml --prune -v
        conda list -n cloe

    - name: Cache pytest cache
      uses: actions/cache@v3
      with:
        path: .pytest_cache
        key: ${{ runner.os }}-pytest-${{ hashFiles('**/environment.yml') }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-pytest-

    - name: Run tests with coverage
      run: |
        pytest --cov=cloe --cov-report=xml
        ls -l coverage.xml
        cat coverage.xml | head -20

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: coverage.xml
        flags: unittests
        fail_ci_if_error: true
