name: CI Pipeline

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/testarnyttnamn/likelihood-implementation
  IMAGE_TAG: latest
  FULL_IMAGE: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

jobs:
  test_in_container:
    name: Test (container)
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Prepare Docker image
        run: |
          echo "➡️ Trying to pull pre-built image..."
          if ! docker pull "$FULL_IMAGE"; then
            echo "⚠️ Pull failed—building image locally."
            docker build -t "$FULL_IMAGE" .
          fi

      - name: Run pytest inside container
        run: |
          docker run --rm \
            -v "${{ github.workspace }}":/src \
            -w /src \
            "$FULL_IMAGE" \
            bash -lc "pytest --verbose --pycodestyle --pydocstyle \
                       --junitxml=pytest.xml \
                       --cov=./ --cov-report=term --cov-report=xml=coverage.xml"

      - uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: pytest.xml

      - uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

  build_and_push_image:
    name: Build & Publish Image
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build & Push Docker image
        run: |
          echo "🔨 Building image $FULL_IMAGE"
          docker build -t "$FULL_IMAGE" .
          echo "📤 Pushing to GHCR"
          docker push "$FULL_IMAGE"
