name: CI

on:
  push:
    branches:
      - master
      - main
      - ci-debug
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Remove pyhmcode from environment.yml on CI
      if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
      run: |
        sed -i '/pyhmcode/d' environment.yml

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip build-essential make gfortran python-is-python3 python3-dev

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.9
        activate-environment: cloe
        environment-file: environment.yml
        use-mamba: true

    - name: Manually install pytest and pytest-cov
      run: conda install -n cloe pytest pytest-cov -y

    - name: Debug conda env update
      run: |
        conda env update -n cloe -f environment.yml --prune -v
        conda list -n cloe

    - name: Cache pytest cache
      uses: actions/cache@v3
      with:
        path: .pytest_cache
        key: ${{ runner.os }}-pytest-${{ hashFiles('**/environment.yml') }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-pytest-

    - name: Create dummy hmcode module patch
      run: |
        cat << EOF > dummy_hmcode.py
import sys
import types

class DummyHMCode(types.ModuleType):
    def __getattr__(self, name):
        def dummy(*args, **kwargs):
            return None
        return dummy

sys.modules['hmcode'] = DummyHMCode('hmcode')
EOF

    - name: Run tests with coverage and dummy hmcode patch
      run: |
        python -c "import dummy_hmcode" -m pytest --cov=cloe --cov-report=xml
        ls -l coverage.xml
        head -20 coverage.xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: coverage.xml
        flags: unittests
        fail_ci_if_error: true
