name: CI via Pre-built Docker Image

on:
  push:
    branches:
      - ci-debug
      - master
  pull_request:
    branches:
      - ci-debug
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Match the exact tag you just pushed above
      - name: Determine tag
        run: |
          if [ "$GITHUB_REF" = "refs/heads/master" ]; then
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=ci-debug" >> $GITHUB_ENV
          fi

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Pull pre-built image
        run: docker pull ghcr.io/testarnyttnamn/testnamemaster:${{ env.IMAGE_TAG }}

      - name: Run tests inside container
        run: |
          docker run --rm \
            -v "${{ github.workspace }}":/src \
            -w /src \
            ghcr.io/testarnyttnamn/testnamemaster:${{ env.IMAGE_TAG }} \
            bash -lc "pytest --verbose --pycodestyle --pydocstyle \
                       --junitxml=pytest.xml --cov=./ \
                       --cov-report=term --cov-report=xml=coverage.xml"

      - name: Upload JUnit report
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: pytest.xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
