name: CI via Pre-built Docker Image

on:
  push:
    # run on master or any feature branch (e.g. ci-debug)
    branches: [ master, ci-debug ]
    paths:
      - 'cloe/**'
      - 'configs/**'
      - 'environment.yml'
      - 'setup.cfg'
      - '.github/workflows/ci.yml'
      - 'setup.py'
  pull_request:
    branches: [ master, ci-debug ]
    paths:
      - 'cloe/**'
      - 'configs/**'
      - 'environment.yml'
      - 'setup.cfg'
      - '.github/workflows/ci.yml'
      - 'setup.py'
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      # If on master, use `latest`, else branch name (ci-debug, etc.)
      IMAGE_TAG: ${{ github.ref == 'refs/heads/master' && 'latest' || github.ref_name }}
      PYTHONUNBUFFERED: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Pull image & run tests inside container
        run: |
          IMAGE=ghcr.io/testarnyttnamn/testnamemaster:${{ env.IMAGE_TAG }}
          echo "→ Pulling $IMAGE"
          docker pull "$IMAGE"

          echo "→ Running pytest in container"
          docker run --rm \
            -v "${{ github.workspace }}":/src \
            -w /src \
            "$IMAGE" \
            bash -lc "conda activate cloe && \
                       pytest --verbose \
                              --pycodestyle \
                              --pydocstyle \
                              --junitxml=pytest.xml \
                              --cov=./ \
                              --cov-report=term \
                              --cov-report=xml=coverage.xml"

      - name: Upload JUnit report
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: pytest.xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
