name: CI via Pre-built Docker Image

on:
  pull_request:
    branches:
      - ci-debug
    paths:
      - 'cloe/**'
      - 'configs/**'
      - 'environment.yml'
      - 'setup.cfg'
      - 'setup.py'
      - '.github/workflows/ci.yml'
  push:
    branches:
      - ci-debug
    paths:
      - 'cloe/**'
      - 'configs/**'
      - 'environment.yml'
      - 'setup.cfg'
      - 'setup.py'
      - '.github/workflows/ci.yml'
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read       # read your code
      packages: read       # pull from GHCR

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Pull & Run tests inside container
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/testnamemaster:ci-debug
          docker pull "$IMAGE"
          docker run --rm \
            -v "${{ github.workspace }}":/src \
            -w /src \
            "$IMAGE" \
            bash -lc "pytest --verbose --pycodestyle --pydocstyle --junitxml=pytest.xml --cov=./ --cov-report=term --cov-report=xml=coverage.xml"

      - name: Upload JUnit report
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: pytest.xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
