# .github/workflows/ci-option2.yml
name: CI via Pre-built Docker Image

on:
  pull_request:
    paths:
      - 'cloe/**'
      - 'configs/**'
      - 'environment.yml'
      - 'setup.cfg'
      - '.github/workflows/ci-option2.yml'
      - 'setup.py'
  push:
    branches:
      - main
    paths:
      - 'cloe/**'
      - 'configs/**'
      - 'environment.yml'
      - 'setup.cfg'
      - '.github/workflows/ci-option2.yml'
      - 'setup.py'
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitLab Container Registry (insecure)
        run: |
          echo "${{ secrets.TESTING }}" \
            | docker login registry.gitlab.euclid-sgs.uk \
                --username sjoudaki \
                --password-stdin \
                --tls-verify=false

      - name: Pull pre-built image (insecure)
        run: |
          IMAGE=registry.gitlab.euclid-sgs.uk/pf-ist-likelihood/likelihood-implementation:latest
          docker --tls-verify=false pull "$IMAGE"

      - name: Run tests inside container
        run: |
          IMAGE=registry.gitlab.euclid-sgs.uk/pf-ist-likelihood/likelihood-implementation:latest
          docker --tls-verify=false run --rm \
            -v "${{ github.workspace }}":/src \
            -w /src \
            "$IMAGE" \
            bash -lc "\
              pytest --verbose \
                     --pycodestyle \
                     --pydocstyle \
                     --junitxml=pytest.xml \
                     --cov=./ \
                     --cov-report=term \
                     --cov-report=xml=coverage.xml
            "

      - name: Upload JUnit report
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: pytest.xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
