name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gfortran make

      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          environment-file: environment.yml
          activate-environment: cloe
          python-version: 3.9
          use-mamba: true

      - name: Run tests with coverage
        run: |
          python -m pytest --cov=cloe --cov-report=term --cov-report=xml --junitxml=pytest.xml
